##  Dockerfile文件格式

# This dockerfile uses the ubuntu image
# VERSION 2 - EDITION 1
# Author: docker_user
# Command format: Instruction [arguments / command] ..
 
# 1、第一行必须指定 基础镜像信息
FROM ubuntu:15.04
 
# 2、维护者信息
MAINTAINER docker_user 564299175@qq.com
 
# 3、镜像操作指令
RUN echo "Hello world" > /tmp/newfile
 
# 4、容器启动执行指令
#CMD /usr/sbin/nginx